source 'https://rubygems.org'

ruby '3.2.2'

gem 'sinatra', require: 'sinatra/base'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'puma'
gem 'rerun'
gem 'rake'
gem 'pry'
gem 'jsonapi-serializer'
gem 'csv'
gem 'rackup'
gem 'rack-cors'
gem 'bcrypt'
gem 'jwt'
gem 'dotenv'

group :test do 
  gem 'database_cleaner-active_record'
  gem 'rspec'
  gem 'rack'
  gem 'rack-test'
  gem 'factory_bot'
  gem 'faker'
  gem 'simplecov'
end